[package]
name = "mutica-py"
version = "0.1.0"
edition = "2024"

[dependencies]
mutica = "0.2.1"
pyo3 = { version = "0.27.1", features = ["extension-module"] }
tokio = "1.48.0"

[lib]
name = "mutica_py"
crate-type = ["cdylib"]
[package.metadata.maturin]
name = "mutica_py"
