[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "mutica-py"
version = "0.1.0"
description = "Python bindings for the Mutica library"
authors = [{ name = "sjrsjz", email = "sjrsjz@gmail.com" }]
dependencies = []
